# Generated by Django 3.2 on 2023-02-28 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_review_unique review'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='Unique review',
        ),
    ]
