# Generated by Django 3.2 on 2023-05-21 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_review_unique review'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='reviews_cat_name_84397e_idx'),
        ),
        migrations.AddIndex(
            model_name='genre',
            index=models.Index(fields=['name'], name='reviews_gen_name_0e1109_idx'),
        ),
        migrations.AddIndex(
            model_name='title',
            index=models.Index(fields=['name'], name='reviews_tit_name_2b1433_idx'),
        ),
        migrations.AddIndex(
            model_name='title',
            index=models.Index(fields=['year'], name='reviews_tit_year_a04313_idx'),
        ),
        migrations.AddIndex(
            model_name='title',
            index=models.Index(fields=['category'], name='reviews_tit_categor_462c42_idx'),
        ),
    ]
